### ISSUE TITLE
Square box is not displaying to check(tick) in checkbox field element

### ISSUE THREAD

**Issue by sushama20** [IBM/carbon-components-builder#82]
Square box is not displaying to check after exporting on UI

<img width="1255" alt="checkbox-error" src="https://user-images.githubusercontent.com/43578026/169554595-67daabe7-3c98-4e86-8b83-aedea84dc50b.png">

**Comment by sushama20** [comment]
In the fragment design it is visible
<img width="862" alt="fragment" src="https://user-images.githubusercontent.com/43578026/169556391-043d2a46-e818-48ec-a976-539a64ac6d09.png">
.

**Comment by zvonimirfras** [comment]
@sushama20, I tried a couple of different layouts but I can't replicate this. It always exports correctly and looks as expected on codesandbox.

What are the steps to reproduce this?

**Comment by sushama20** [comment]
Issue was occurring since we did not import the modules properly.
It is fixed now.
Thank you !!
